version: '3'

services:
  zookeeper1:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "my_topic:1:3"
      KAFKA_ADVERTISED_PORT: "9092"
     
  jaeger-allinone:
    image: jaegertracing/all-in-one:1.7
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
  
  discovery-server:
    container_name: discovery-server
    image: mani875/urban_clap:discoveryserver
    ports:
    - "8761:8761"
    
  api-gateway:
    container_name: api-gateway
    image: mani875/urban_clap:apigateway
    ports:
        - "9999:9999"
    links:
        - discovery-server:discovery-server
    environment:
        - EUREKA_URI=http://discovery-server:8761/eureka
    volumes:
        - /tmp:/workspace/logs   
  
  order-service:
    container_name: order-service
    image: mani875/urban_clap:orderservice
    ports:
        - "8081:8081"
    depends_on:
        - "kafka"
    links:
        - discovery-server:discovery-server
        - kafka
    environment:
        - EUREKA_URI=http://discovery-server:8761/eureka
        - KAFKA_URI=http://kafka:9092
    volumes:
        - /tmp:/workspace/logs   

  user-service:
    container_name: user-service
    image: mani875/urban_clap:userservice
    ports:
        - "8110:8110"
    links:
        - discovery-server:discovery-server
    environment:
        - EUREKA_URI=http://discovery-server:8761/eureka
    volumes:
        - /tmp:/workspace/logs
  
  provider-service:
    container_name: provider-service
    image: mani875/urban_clap:providerservice
    ports:
        - "8115:8115"
    links:
        - discovery-server:discovery-server
    environment:
        - EUREKA_URI=http://discovery-server:8761/eureka  
    volumes:
        - /tmp:/workspace/logs